### ISSUE TITLE
acs_income getting HTTP 404

### ISSUE THREAD

**Issue by davidfasel** [cole-brokamp/DeGAUSS#13]
First off, DeGAUSS is awesome. 👍 

When running degauss/acs_income, I get the 404 error below.  Maybe the api.census.gov API format has changed?

---------------------
downloading Median household income in the past 12 months (in 2015 Inflation-adjusted dollars) from 2015 5-year American Community Survey

Error in open.connection(con, "rb") : HTTP error 404.
Calls: map_df ... fromJSON_string -> parseJSON -> parse_con -> open -> open.connection
Execution halted

**Comment by cole-brokamp** [comment]
Thanks for the notice.  You're right, it looks they updated the API endpoint. I'm going to push a change right now that should fix it.

**Comment by cole-brokamp** [comment]
You can wait for the auto build to be done before you pull it again: https://hub.docker.com/r/degauss/acs_income/builds

**Comment by davidfasel** [comment]
It worked!  Thanks for fixing this so quickly.
