### ISSUE TITLE
readOGR error in degauss/census_tracts

### ISSUE THREAD

**Issue by Dolan-Brian** [cole-brokamp/DeGAUSS#15]
I'm getting the following error when running the census_tracts image: 
`Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  :
  Cannot open layer
Calls: %>% ... readOGR -> suppressMessages -> withCallingHandlers -> ogrInfo
In addition: Warning message:
In unzip(file_loc, exdir = cache_dir, overwrite = TRUE) :
  error 1 in extracting from zip file`
While my file includes quite a few counties, I don't believe its a timing out issue.

**Comment by cole-brokamp** [comment]
This is an issue related to us rolling back to the a stable version due to the problem with the "tigris" package not being installable in some of the later versions.  Let me cherry-pick the fix for this one and push up a new image.

**Comment by Dolan-Brian** [comment]
This might also be a timeout issue. I reduced the number of counties and it worked perfectly!

**Comment by cole-brokamp** [comment]
just pushed it up... can you `docker pull degauss/census_tracts:latest` and try again?

**Comment by cole-brokamp** [comment]
closing for now since your immediate problem was solved, let me know if anything else comes up!
