### ISSUE TITLE
Census Tracts: Request Access Denied

### ISSUE THREAD

**Issue by Dolan-Brian** [cole-brokamp/DeGAUSS#17]
Subject line captures it all. When trying to pull the geocoded_census_tracts image, I get the following error message: `pull access denied for degauss/geocoded_census_tracts, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.`

The interesting part is I can pull the geocoding image without issue. Thanks!

**Comment by cole-brokamp** [comment]
Looks like you might possibly be using the wrong name and that’s why you’re getting the error that the repo doesn’t exist. There’s no “geocoded_” in the image name. Can you please paste the code you’re using to try to pull the image?

**Comment by Dolan-Brian** [comment]
Wow, sorry to bother you with such a trivial mistake! Thanks for your quick reply!
