### ISSUE TITLE
Error :cannot open the connection

### ISSUE THREAD

**Issue by Amro-Hassan** [cole-brokamp/DeGAUSS#19]
Hi Cole,

Thank you so much for all your help, After fixing the Address column name, I got this error when I executed the code 
My code 
docker run --rm=TRUE -v "%cd%":/tmp degauss/geocoder GeoCodes.csv Address

Error below

Loading required package: methods
Error in fifo(tempfile(), open = "w+b", blocking = T) :
  cannot open the connection
Execution halted

**Comment by cole-brokamp** [comment]
Please see here: https://github.com/cole-brokamp/DeGAUSS/wiki/Microsoft-Windows-Problems-and-Workarounds#parallel-computing-on-windows
