### ISSUE TITLE
incorrectly geocoded when zip code greater than 5-digits

### ISSUE THREAD

**Issue by gifforda** [cole-brokamp/DeGAUSS#3]
I think I've found an issue which causes addresses to be incorrectly geocoded. In the geocoding tips, it says "plus4 zip codes are ignored". To me this means that if the zip code has more than 5 digits, the additional digits after the first 5 will be ignored. However, it appears that this is not the case. I’m not sure how the zip codes are being determined but, attached is an example of the input and output. Am I missing something here?
Thanks!
[zip_code_issue.pdf](https://github.com/cole-brokamp/DeGAUSS/files/886211/zip_code_issue.pdf)

**Comment by cole-brokamp** [comment]
Could you supply the full address including the city/state and street name/number that are giving you the results? It would be easier to troubleshoot if I could reproduce the problem.

**Comment by gifforda** [comment]
I'll have to redo the geocoding with other addresses, as the addresses which produced these results are protected and I can't publish the complete addresses here. 
I'll put the results here when I've redone the geocoding with unprotected addresses.

**Comment by gifforda** [comment]
Here are the results for 10 addresses showing the same issue. 
There are 2 files, each containing the same 10 addresses, one file has short zip codes, and one has long zip codes. The files were each processed through the following 4 DeGAUSS docker images in this order: geocoder, census_tracts, acs_income, dist_to_major_roadway
The two csv files attached here include all the resulting output columns from running these docker images. 
Also I'm working with the latest docker images.
[test_addresses_geocoding_completed_short_zipcode.txt](https://github.com/cole-brokamp/DeGAUSS/files/886761/test_addresses_geocoding_completed_short_zipcode.txt)
[test_addresses_geocoding_completed_long_zipcode.txt](https://github.com/cole-brokamp/DeGAUSS/files/886762/test_addresses_geocoding_completed_long_zipcode.txt)

**Comment by cole-brokamp** [comment]
It looks like the address parser is having trouble identifying the five digit zip from a nine digit number string because it is expecting addresses as usually reported in a mailing address. These should include a hyphen after the 5 digit and before the 4 digit zip, i.e. `37209-0000` instead of `372090000`.  Geocoding using one of your examples shows the equivalent between this and only using the 5 digit zip:

```
  > docker run --rm=TRUE degauss/geocoder_slim "4113 Utah Ave Nashville, TN 372090000"
[{"street":"Tina Loop","zip":"41740","city":"Tina","state":"KY","lat":37.366801,"lon":-83.019154,"fips_county":"21119","score":0.366,"prenum":"","number":"199","precision":"street"}]
  > docker run --rm=TRUE degauss/geocoder_slim "4113 Utah Ave Nashville, TN 37209-0000"
[{"street":"Utah Ave","zip":"37209","city":"West Nashville","state":"TN","lat":36.144193,"lon":-86.835335,"fips_county":"47037","score":0.957,"prenum":"","number":"4113","precision":"range"}]
  > docker run --rm=TRUE degauss/geocoder_slim "4113 Utah Ave Nashville, TN 37209"
[{"street":"Utah Ave","zip":"37209","city":"West Nashville","state":"TN","lat":36.144193,"lon":-86.835335,"fips_county":"47037","score":0.957,"prenum":"","number":"4113","precision":"range"}]
```
You can see that it picks the zip code as `41740` instead of `37209` in the first call, but gets it right in the second and third calls.

I'll update the geocoding documentation to make this clearer. Thanks for raising the issue.
