### ISSUE TITLE
parse error: premature EOF - what causes this ? 

### ISSUE THREAD

**Issue by gifforda** [cole-brokamp/DeGAUSS#4]
When running the acs_income image, occasionally when it gets to the end of the processing it quits and gives the following error:
**_(long list of zip codes....i.e: 
18013...
13241...
followed by:)
downloading Median household income in the past 12 months (in 2015 Inflation-adjusted dollars) from 2015 5-year American Community Survey
Error in parse_con(txt, bigint_as_char) : parse error: premature EOF                                       
                     (right here) ------^
Calls: map_df ... <Anonymous> -> fromJSON_string -> parseJSON -> parse_con -> .Call
Execution halted_**
Re-running the image on the same file multiple times does not change the output - i.e. it is not a matter of just re-running the process and it eventually works. It always fails. Also, the processing appears to get through the complete list of zip codes before quitting. Any ideas what might be causing this?

**Comment by cole-brokamp** [comment]
likely a non alpha numeric character present in the address fields. these can wreak havok on geocoding results and should be omitted before processing them. see: https://github.com/cole-brokamp/geocoder/issues/1

**Comment by gifforda** [comment]
I already removed all addresses with non alpha numeric characters, as indicated in geocoding tips you provided on the DeGAUSS website. 
So I checked the list of processed counties (i noticed it's counties, not zip codes that are listed in the acs_income docker image output), and one county is missing. Assuming that the address connected to this county is possibly causing the issue I looked at the file which is being fed into the acs_income image, only one address is in that missing county, and there isn't anything different in that address from any other addresses in the file. The address was successfully processed through the geocoder and census tract docker images. 
I'm trying other possibilities now...

**Comment by gifforda** [comment]
Here's a list of things I've tried, sort of randomly, trying to figure out what might be causing the error.
Each of these was tried separately. i.e. the addresses removed in step 1 were put back before removing the addresses in step 2, and so on, such that I could better determine which addresses were causing the issue.

1. Removed addresses in Puerto Rico, thinking that the acs income docker image might not work in Puerto Rico - the error still occurred.
1. Removed addresses where the geocoded output "zip" contained "NA" - the error still occurred.
1. Removed addresses where the geocoded output "city", "state", "street1", and "street2" all contained "NA" - the error still occurred.
1. Removed addresses where the geocoded output "city", "state", "street1", "street2", "prenum" and "number" all contained "NA" - the data was processed successfully!  

So... my question is - does this make sense? How come the acs_income docker image can't calculate the 2015 ACS income for these troublesome addresses in step 4, given that they all have valid "zip", "city", "state", "score", "precision", "county", "tract", "lon", and "lat" outputs ?

Thanks!

**Comment by cole-brokamp** [comment]
Hi,  The `acs_income` images relies on valid lat/lon coordinates and does not use any of the fields you listed above to determine which census tract that row is in.  Can you give an example address where the image fails and I can try to troubleshoot it?

**Comment by gifforda** [comment]
So... the addresses which were removed in step 4 (above) **do** have valid lat/lon coordinates. My comment above may not have been clear. What I mean is that for a given batch of addresses, when I remove the addresses  from the batch, which satisfy the rule indicated in step 4, the remaining addresses process in acs_income successfully.  The addresses indicated in step 4, which were removed, do have valid lat/lon coordinates. 
  
Also, I can't share the addresses here, as they are patient addresses and are therefore private. However, I checked a few of the lat/lon pairs for the addresses which could not be processed with acs_income and the lat/lon pairs appear to be valid. For example, one of the addresses is in Clarksville TN and was geocoded with "precision" = "city". When I map the geocoded lat/lon pair for that address in Google, it is the center of Clarksville TN.

**Comment by cole-brokamp** [comment]
Addresses geocoded with a `precision` of anything other than `range` or `street` should *not* be used for further analysis, including extracting census tract or median household income.  For example, the address that was geocoded with a `precision` of `city` means that the geocoder used the centroid of the city of Clarksville TN, as the geocoded location which is highly unlikely that that is where the subject's address actually is.  

Also, be careful about using PHI on the internet.  Its good that you're not posting private addresses here, but you also should probably not share them with everyone at Google!

Its hard to image a scenario where the geocoder assigns a missing value for `city`, `state`, `street1`, `street2`, `prenum` and `number`, but assigns valid lat/lon coordinates using a `precision` method of `range` or `street`. If it is, its likely a bug with the geocoder, but I can't say for sure without being able to reproduce the problem locally.
