### ISSUE TITLE
Unable to use DeGAUSS through Docker Quickstart Terminal

### ISSUE THREAD

**Issue by lmikaelian** [cole-brokamp/DeGAUSS#9]
I'm having trouble getting the geocoder to work using the sample .csv from the readme. Running on Windows 10 Home with the Docker Quickstart Terminal I get the following, presumably R error:

![image](https://user-images.githubusercontent.com/21689539/40199361-30d827b8-59e7-11e8-8785-1431591157ae.png)

A colleague of mine that's on macOS was able to get the same operation to run on Docker Terminal without issue.

**Comment by cole-brokamp** [comment]
Yes, it seems like the R program cannot find the `test_2.csv` in the working directory. Unfortunately, I don't have access to a windows machine to try and reproduce the problem.  Can you maybe try from another directory and see if you get the same error?

You could also override the entry point of the container and get a bash prompt to change to the `/tmp` directory and `ls` to make sure the volume is mounting okay between the host system and the container.  That would allow us to isolate the problem down to either R or the Docker installation.

**Comment by lmikaelian** [comment]
I've tried from different directories with the same outcome every time. I'll read up on the entrypoint override and try it out. Thanks!

**Comment by cole-brokamp** [comment]
Thanks, this could be a Windows 10 issue too.  I hope that we will be supporting Windows 10 soon, I will update you if we do. Are you using Docker CE integrated into Windows 10?  Or are you using Docker Toolbox?

**Comment by cole-brokamp** [comment]
Closing for now, @lmikaelian, please let us know if you follow up on this
